### PR TITLE
Added Archive of the Sealed Gods and Genso Flood Front

### PR DESCRIPTION
**Pull request by Pinky-Cat**
With esoteric Touhou website Archive of the Sealed Gods added to the index, I am starting to see that perhaps a new category for "Critical Analysis" for websites that discuss upon the themes of Touhou could be added under Information. There isn't enough for the category to exist, however.

### CODE REVIEW

**Comment by Pinky-Cat** [comment]
Need to go review on the content of Archive of the Sealed Gods since I have been informed that its image board origins may of poisoned its information.

**Comment by Pinky-Cat** [comment]
Now that I have reviewed the work in question, there is nothing harmful about it aside from its connection to 4chan. However, aside from some language phases coming from imageboard culture, the work does not recommend anything dangerous despite its connection to 4chan and in fact does the opposite. I let you decide if Spirituality has any place on this list.

**Comment by Raxelgrande** [comment]
I agree that a "Critical Analysis" category is a good idea as soon as we have more links about it. Maybe linking to forum users and threads that discuss this sort of thing could do?

**Comment by Pinky-Cat** [comment]
It definitely would be a good idea to include user threads in Critical Analysis.

Digging up some saved Reddit posts and finding that “[Analysing DDC: Reversing the Ideology of Touhou](https://www.reddit.com/r/touhou/comments/wid6dk/analysing_ddc_reversing_the_ideology_of_touhou/)” would be a good addition to such a category on critical analysis on Touhou itself.
On the other hand, I would like to highlight any of the posts by [CountVonNumenor](https://moriyashrine.org/profile/27680-countvonnumenor/) whose questions on the Touhou community were very enlightening, despite the lackluster discussion from r/Touhou.

**Pull request merged**
